real_esrgan_x2:
  scale: 2
  weights_path: "real_esrgan/weights/RealESRGAN_x2plus.pth"
  params:
    {
      num_in_ch: 3,
      num_out_ch: 3,
      num_feat: 64,
      num_block: 23,
      num_grow_ch: 32,
      scale: 2,
    }

real_esrgan_x4:
  scale: 4
  weights_path: "real_esrgan/weights/RealESRGAN_x4plus.pth"
  params:
    {
      num_in_ch: 3,
      num_out_ch: 3,
      num_feat: 64,
      num_block: 23,
      num_grow_ch: 32,
      scale: 4,
    }

nafnet_realblur:
  scale: 1
  weights_path: "naf_net/weights/run_3/nafnet_real_blur_val_psnr=28.34.ckpt"
  params:
    {
      width: 32,
      enc_blk_nums: [1, 1, 1, 28],
      middle_blk_num: 1,
      dec_blk_nums: [1, 1, 1, 1],
    }

nafnet_sidd:
  scale: 1
  weights_path: "naf_net/weights/NAFNet-SIDD-width32.pth"
  params:
    {
      width: 32,
      enc_blk_nums: [2, 2, 4, 8],
      middle_blk_num: 12,
      dec_blk_nums: [2, 2, 2, 2],
    }

stripformer:
  scale: 1
  weights_path: "stripformer/weights/Stripformer_realblur_R.pth"

mlwnet:
  scale: 1
  weights_path: "mlwnet/weights/realblur_j-width32.pth"
  params: { dim: 32 }

ufpdeblur:
  scale: 1
  weights_path: "ufpdeblur/weights/net_g_latest.pth"
  params:
    {
      width: 64,
      enc_blk_nums: [1, 1, 1, 28],
      middle_blk_num: 1,
      dec_blk_nums: [1, 1, 1, 1],
    }

swinir_x4:
  scale: 4
  weights_path: "swinir/weights/003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x4_GAN.pth"
  params:
    {
      upscale: 4,
      in_chans: 3,
      img_size: 64,
      window_size: 8,
      img_range: 1.,
      depths: [6, 6, 6, 6, 6, 6],
      embed_dim: 180,
      num_heads: [6, 6, 6, 6, 6, 6],
      mlp_ratio: 2,
      upsampler: "nearest+conv",
      resi_connection: "1conv",
    }

hat_x4:
  scale: 4
  weights_path: "hat/weights/Real_HAT_GAN_SRx4.pth"
  params:
    {
      upscale: 4,
      in_chans: 3,
      img_size: 64,
      window_size: 16,
      compress_ratio: 3,
      squeeze_factor: 30,
      conv_scale: 0.01,
      overlap_ratio: 0.5,
      img_range: 1.,
      depths: [6, 6, 6, 6, 6, 6],
      embed_dim: 180,
      num_heads: [6, 6, 6, 6, 6, 6],
      mlp_ratio: 2,
      upsampler: "pixelshuffle",
      resi_connection: "1conv",
    }

drct_x4:
  scale: 4
  weights_path: "drct/weights/Real_DRCT_GAN_SRx4_finetuned_from_mse_net_g_latest"
  params:
    {
      upscale: 4,
      in_chans: 3,
      img_size: 64,
      window_size: 16,
      compress_ratio: 3,
      squeeze_factor: 30,
      conv_scale: 0.01,
      overlap_ratio: 0.5,
      img_range: 1.,
      depths: [6, 6, 6, 6, 6, 6],
      embed_dim: 180,
      num_heads: [6, 6, 6, 6, 6, 6],
      mlp_ratio: 2,
      upsampler: "pixelshuffle",
      resi_connection: "1conv",
    }
